name: 🎉 Release Binary
on:
  schedule:
  - cron: 0 2 * * *
  

jobs:
  release:
    runs-on: debian-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Setup Dependencies
        run: sudo apt-get install libpcap-dev 

      - name: Setting up ProjectDiscovery tools
        env:
          GO111MODULE: on
        run: |
          go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder
          go get -v github.com/projectdiscovery/dnsx/cmd/dnsx
          go get -v github.com/projectdiscovery/naabu/v2/cmd/naabu
          go get -v github.com/projectdiscovery/httpx/cmd/httpx
          go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei
          go get -v github.com/projectdiscovery/mapcidr/cmd/mapcidr
          go get -u github.com/ffuf/ffuf
        shell: bash
      
      - name: "Create release on GitHub"
        uses: goreleaser/goreleaser-action@v3
        with: 
          args: "release --rm-dist"
          version: latest
          workdir: .
        env: 
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
